### ISSUE TITLE
Authentication Enhancement

### ISSUE THREAD

**Issue by JackLidge** [SamirStandnes/gdrive_sync_folder_script#1]
Hi there,

I found this repo after reading [your article](https://medium.com/swlh/sync-a-folder-on-your-computer-to-google-drive-with-python-5155e73e18ca) and it seemed to do pretty much everything I need to backup some databases at work. 

However, as I'll be running my script periodically from the command line, I need it to authenticate automatically (at least after an initial authentication). I'm currently working on adding this in, I can do a pull request once this functionality is added.

I've also got a few other thoughts about things I'd like to implement to expand my use case which might require some significant rewrites. Would you prefer me to do this via adding pull requests here or just forking this repo and keeping changes in there to myself?

**Comment by SamirStandnes** [comment]
Hi there,

I apologize for the late response. 

It would be great if you could do a pull request for the automatic authentification functionality!  

As for the other things you'd like to implement, forking works best I think. 

Thank you so much for reaching out.

**Comment by JackLidge** [comment]
Hi,

Since I left that comment, I've made quite a few changes, and ended up moving to a new repo which can be found [here](https://github.com/JackLidge/GDriveSync). The README needs updating and linking to this repo and I need to add a license, but other than that it is the finished version for my use case now.

**Comment by SamirStandnes** [comment]
Hi,
Awesome stuff. Also, thank you for the mention.
